### PR TITLE
Player accessibility

### PR DESCRIPTION
**Pull request by cayb0rg**
### Adds keyboard navigation and partial screenreader accessibility to the player
**Why partial?** Describing destinations for the screenreader has not been implemented. It is possible we can add an additional input box in the creator for the author to add their own descriptions. For example, in the world map demo, the author could describe a label with some fact about that country or even describe the physical location: "Northern country east of the Atlantic Ocean", etc. This would essentially turn the game into Matching, but at least unsighted users could play.

**Update**: Added optional label descriptions to the creator. Screenreader accessibility is left up to the author to make labels make sense.

* New keyboard controls added to instructions:
  * Tab key: Move between terms
    * For screenreaders, this will read Tab key or Arrow keys.
  * Arrow Keys: After focusing a term, use these keys to move between labels
    * For screenreaders, this will read "A" and "D" keys because the arrow keys are reserved
  * Enter/Space: Assign a term to a label
  * ~~Escape~~ "H": Open/Close the instructions
  * R key: Return all labels to the term list
* Auto focuses the submit button after all terms have been assigned
* Auto focuses the next term in the list after you assign a term
* Re-focuses the player on the last active element after leaving a dialog
* Updates button colors in dialogs
* Changes for the screenreader:
  * Hides game board when a dialog appears and vice versa
  * Attaches aria-labels to terms with their title and placement status
  * Attaches aria-labels to labels with their destination index and if it is empty or not (totally useless information)
  * Adds aria-visible-only headers for placed and unplaced labels to indicate number of unplaced and placed labels
  * Adds aria-live updates indicating that a label was placed, that a label replaced another label, that a label wasn't moved upon hitting Enter, and that all labels have been placed
  * Added alt text requirement to the creator and alt text to image in player

**Question on destination navigation**: should the player cycle through unfilled destinations first, or would this be too confusing?

### To-Do
* ~~More descriptive labels~~

### CODE REVIEW

**Comment by FrenjaminBanklin** [comment]
Everything looks really good and keyboard interactions are great, only a couple of minor things I can think of:

- The screen reader is not actually reading out the keyboard instructions, at least in Chrome. I tend to deal with this by just setting the `aria-label` of the keyboard instructions (or whatever the nearest convenient element is that is reachable in the tab order) to the full text of the keyboard instructions so unsighted users don't even have to open a dialog to get the information.
- If the keyboard instructions are opened outside of the intro dialog, the labels are still reachable in the tab order.

As for the order in which destinations are cycled through, I think the current approach of keeping them in a predictable order all the time would be better than the order changing depending on whether some of them are unassigned or not.

**Comment by cayb0rg** [comment]
Nice catches. The latest changes include:
* Optional label descriptions in the creator that are read aloud via the aria-live region in the player
* "Let me finish" button is focused first on Submit Answers
* Can no longer tab out of the dialog into the game
* Changed Escape hotkey to the "H" key since that is reserved by screenreaders
* Adds instructions in an aria-label on the "Got It" button

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
This is well beyond what I expected us to implement, so kudos for taking it on. A few minor issues:

Player:
-  There's some weirdness with the hover/pending states for labels, visually. If I drag and drop a label, the "ghost" label underneath it persists until I move the cursor away. I can also get labels into a permanent reduced opacity state by dragging it off a destination and then snapping it back on to the same destination. Cleaning these state transitions up a bit will go a long way.
- Pressing "R" to reset all labels doesn't appear to trigger any sort of live region notification, and it also doesn't appear to clear the label text indicating where they were placed. If I select a label after they've all been unset with "R", it still says it's located at destination so-and-so.

Creator:
- The placeholder text is good but I'm not crazy about how it disappears completely once the input is interacted with. Ideally, the placeholder text should remain until the input has a string value > 0.
- It may be prudent to add some kind of visual reminder to set the image description once an image is selected, either a toast or a little message at the top or bottom or something.

Misc:
- Make sure the qset additions are backwards compatible (the widget won't freak out if the qsets don't possess those values), it looked like you were handling that appropriately but it's vital to make sure.
- The demo could use descriptions for the label drop points, since it should be indicative of a well-designed labeling widget.

**Comment by cayb0rg** [comment]
Creator
* Fixed placeholder text disappearing on click
* Fixed placeholder text not reappearing after an input loses focus and is empty
* Image description changer will now appear after importing an image. For existing widgets, an arrow will point to the image description changer
* Checked that the qset additions are conserved in save and load operations with both new and old qsets; realized I need to put label descriptions in ``options`` instead of ``question``. Thanks for the heads up! 

Player
* Fixed issue with labels staying in ghost state if placed at same destination
* Aligned ghost label with dropped label
* Fixed "R" not resetting aria-labels
* Added demo label descriptions

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
Really phenomenal work here. I think it's pretty much ready to go, only two minor things I've noticed:

- After playtesting, I'm not 100% convinced auto-selecting the next label is the right move when a label is dropped. For one thing, it causes the live region update announcing the placement to be put in queue behind the focus event. For another, it can get a little confusing as to where the focus is switching in response to an input event. Programmatic focus is good, but it almost feels a little overused here. I'd feel more in control if I was the one in charge of tabbing between labels. It can also cause some weird behaviors, like if you hit enter or space immediately when the first label is selected, it will first highlight the first drop point, then drop the label at that point and immediately focus the next label, which will then drop it at the first drop point, etc. Let me know how you feel about this.
- In a few cases I've noticed the line connecting the label to the node becoming vertically decoupled with the label. It's most easily reproduced in the demo when using the arrow keys to switch between drop points:

Screenshot 2023-09-08 at 4 21 31 PM

It's not a big issue, but if you're able to identify and correct it, it'd be a nice bit of final polish.

**Comment by cayb0rg** [comment]
* Agreed. By default, the player will lose focus when placing a label (since labels are being removed and inserted into "placed" or "unplaced" divs), and pressing Tab will then focus the next element. Before, I was essentially removing this step of having to press Tab to return the focus. However, it makes more sense to let the user do this themselves, and removing the auto-focus makes the screen reader output less confusing. 
* Good catch. I forgot to apply styling to hide the assistive alert in the DOM.

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
99% of the way there. Having labels not autofocus definitely feels better, but I'm noticing that tabbing to focus the next unsorted label doesn't focus the one at the top of the list, but a label further down by some offset that appears unintentional. Once that's resolved it looks good to go.

The only other things I'd take care of while this PR is still open: adding the accessibility metadata to the `install.yaml` and replacing the travis configuration with the github workflows used by other widgets.

**Comment by cayb0rg** [comment]
I'll keep thinking on this, but I'm not sure there is anything I can do to focus the first element without manually refocusing, which would read the aria label of the focused label before the ARIA live region update as it did before. It's currently focusing the next label in the list directly after the one the user just moved by default.

**Comment by clpetersonucf** [comment]
Closing, since these were incorporated into #36 which was approved and merged.

**Pull request closed without merging**
